import pygame
from script import load_image
player_image = load_image('image/player')
earth_image = pygame.image.load('image/blocks/earth.png').convert_alpha()
center_image = pygame.image.load('image/blocks/center.png').convert_alpha()
water_image = pygame.image.load('image/blocks/water.png').convert_alpha()
box_image = pygame.image.load('image/blocks/box.png').convert_alpha()
stop_image = pygame.image.load('image/blocks/stop.png').convert_alpha()
enemy_1_image = pygame.image.load('image/enemy/1/1.png').convert_alpha()
enemy_2_image = pygame.image.load('image/enemy/2/1.png').convert_alpha()
enemy_3_image = pygame.image.load('image/enemy/3/1.png').convert_alpha()
enemy_4_image = pygame.image.load('image/enemy/4/1.png').convert_alpha()
portal_image = pygame.image.load('image/portal/Portal_100x100px1.png').convert_alpha()
monetka_image = pygame.image.load('image/item/monetka.png').convert_alpha()
fireball_image = load_image('image/fireball')
fire_image = load_image('image/fire')
nps_image = load_image('image/nps/image')
hp_image = pygame.image.load('image/item/hp.png').convert_alpha()
mp_image = pygame.image.load('image/item/mp.png').convert_alpha()
qwest_1_image = pygame.image.load('image/item/qwest 1.png').convert_alpha()
flag_image = pygame.image.load('image/item/flag.png').convert_alpha()